set number "--shows the current line number with respect to relative number otherwise the current line number becomes zero"
set relativenumber

filetype plugin indent on

syntax on
set title

set tabstop=8
set softtabstop=8
set shiftwidth=8
set noexpandtab
